### ISSUE TITLE
Test are not running

### ISSUE THREAD

**Issue by alexus37** [alexus37/NoriV2Webinterface#13]
2 test is failing!
This happened between the commits of branch django-websockets:
branch task (a5f384e3d5cfdaeaebf02d2be2dca4afee59ab00) (FAILING)
improve progressbar (aa5b141dc3eb08243439ed8dfd030c09e9c441de) (WORKING)

**Comment by moritzschaefer** [comment]
:)

**Comment by alexus37** [comment]
the line 103 in server/noriv2api/views.py causes the crash            ( 'taskId': task.id)
if you change it to  'taskId': 0 then everything works. Please check it!
