### ISSUE TITLE
Improve authenticate response

### ISSUE THREAD

**Issue by alexus37** [alexus37/NoriV2Webinterface#14]
Please update the authenticate response.
`xml
{                          
    "auth": null,                                 
    "user": {                                
        "url": "http://localhost:8000/users/1/",                                                   
        "username": "ax",                                
        "email": "ax@ax.de",                                
        "user_scenes": [                                
            "http://localhost:8000/scenes/1",                                
            "http://localhost:8000/scenes/2"                                
        ],                                
        "password":                                 "pbkdf2_sha256$20000$dPN7TtH9lH5Y$xFuyCnTtJ65JcbwkeuF/Arcw00jp7gdn/08rBhwKux4="                                
    }                                
}      
`
1. Remove the password!!!
2. user_scenes should have the scene title and the url, maybe something like:
`xml
user_scenes": {                                
           "firstScene": "http://localhost:8000/scenes/1",                                
           "scdScene":  "http://localhost:8000/scenes/2"                                
        }                          
`

**Comment by moritzschaefer** [comment]
Hey, just noticed this Issue, but already sent you some stuff on jabber.

alexus37 notifications@github.com schrieb am Fr., 15. Jan. 2016 um
02:27 Uhr:

**Comment by moritzschaefer** [comment]
From Jabber Chat:
um die details aller szenen zu bekommen mach lieber noch einen AJAX request auf GET /scenes. Der Login sollte nicht alle szenen im detail zurück geben(good practice weil das return objekt des logins sonst zu groß wird und manchmal will man eventuell einfach nur den login ohne szenen herunterladen zu müssen.

Pasword fix: [develop b30efb5]
Tests for the other stuff: 6c0e148328705a0fc684e68914c9b36bf8e7e3cf, a1171fe11cf23de09d1c802faa59877864b046c7
