### ISSUE TITLE
save scenes in user directory

### ISSUE THREAD

**Issue by alexus37** [alexus37/NoriV2Webinterface#8]
Save the temporary xml scene in the user directory (makes the obj referencing easier). 
Delete the xml and the exr file after the rendering!

**Comment by moritzschaefer** [comment]
done and tested in 0eb8888689f5040aab541baacbbd23eab99a10c7

**Comment by alexus37** [comment]
The xml should be created in static/USER/ not in the static directory

**Comment by moritzschaefer** [comment]
fixed in 45038acb3bcbcecdb0bba69d5ecd4476f4bec6a9
is this it?
